version: 2
jobs:
  build:
    working_directory: ~/sentiance-backend
    docker:
      - image: circleci/node:8.9.4
      - image: postgres
        environment:
          POSTGRES_USER: sentiance
          POSTGRES_DB: sentiance
          POSTGRES_PASSWORD: sentiance

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - run:
          name: "npm install"
          command: npm i
      - run:
          name: "npm test"
          command: npm t
      - run:
          name: Install aws-cli
          command: |
            sudo apt-get install python-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python get-pip.py
            sudo pip install awscli
